services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: ./src/Api
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://+:8080
    restart: on-failure
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
      - ./initBdd:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8000:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

  # front:
  #   image: front
  #   build: 
  #     context: ../front
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "9000:80"

volumes:
  dbdata:
